apiVersion: v1
kind: ConfigMap
metadata:
  name: telegram
  namespace: games-production
data:
  bot-id: "6842518979"
  bot-username: "SigmaGamesBot"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vk
  namespace: games-production
data:
  app-id: "51986547"
