apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram
  namespace: games-production
spec:
  encryptedData:
    bot-token: AgAFJQn8IjT4BTEWyJq9H2STetRKTxunmKUYphPZkKkGi1vmduhYmyIOplUNMhojyoTvCD4B7iIvUkx2wj6CUJl96kGI1e5oPYAtOjaKFOmy5xTITcOu51b0lWtaWuvwfsw0cYResrvEn33L6oddVYRJIJPS0ZbKB5OBnnEDN7jyyNqizASWYZbjlsAiardO55/Y4R+O7Jt+/yZJ768R5xQdQJYTMrO5Yx53AwRQjo9x7dPEmjqhE+xwisqGrxMQaxDo4Dy2SPQWQgd/kfq2GZG/vkuBSjA5Y0+h80l9ipN5u9tAce/Ds3PcE7my8ZElIi323gk5bMR/+D6DzmHPYDhPbMpVbNvlBSj8yVNFNo+NyuZUVNOzFkR4syQceDWmBNkoKZ0gNAYFeFzG2GTpFAPqRKO7bTc3fk0PraJ2JDqKxOuKuZ9dCH0r46hMW9dRYLicX+6yZ0q2pnEfjFK3MEqVn2XZu+whJe9Sg8uTSbqjgLiBkqtt+MpQdR4Q4LWO/wGk8EeKNnY+QxCurI42EivfieFjUo2rr0r/U4jtorTllpVRPsSZR2SosV0kYwsTIdCCQfMo3MTXPBZS/R0Qb6ySJnTyzVf/1Cab0RjhiRhk+xcZzQXRZ4u7mJKyh3b3szyPG+jPkQBLoSoMJixFCicxM6xfjyA4r+zH9K9LTR08Qh0mzbPGajp3xrUdCD2ZNQeeDwmvMtIKGi9wEUP8268raLSFC3QtoPieOEUkG0+C5f62iQ==
  template:
    metadata:
      name: telegram
      namespace: games-production
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bypass-tokens
  namespace: games-production
spec:
  encryptedData:
    rate-limit: AgA4WoeKjyH6OkKld8hKw99tDExS+U/ENmRzx+hdsEsy4IxETZFO9wckarhKro5nDa6yupNIX6BP0gqtZGwFw15UxtgXW051xrWby0Mlg/ugRS+MqrK0J9eNj0SnZOHRSccX5IMS+jfwpGyFwRaROwa5sEpS3suB871/9U59YtJOD2b0kWG4/MZ2tW+MYKHc4vj/qDefC10nRfq5+NsoqDL6N95qO8bDHT+w6BYEmB5rU9xcBrofLdT/to1kw7QBFExXsoq/o4nOB99r0QP9l8HbSKflHNA8+FSU6/vYXzEcDrzYDocWKFHXGKx1rZ7YdPjhgfS1ACA79mmKsvniUwGPzQyTsNaZbaLFa8qHfav6N/nW28rI8woNngNx2+/qJaFDHtbc0F+qO8OIG626WT3i94iHWPFTMYcabclX+np8Sm9rVblW8cR0RRl2CQeCzGO84qgjf3DCCkJxiGYf/DugW36hzjTdkn0l34IbSVWlhDKWxjB/mrbxN9H4uf4H+MOtvY4l7XBVaOhVuKTa8FcUSx+6dBsX6xDhE7fOOD4lsFFNUw4fbBYcF+utRqeepPGTEz0BmT8vH9BCOxcK9ib5RYFsYij3YRtaVcWjMtwsR8Ta9mhv2iQnvo0m4hMoAgEQSOzT8Hq9OOiJRCHK4vw3RTh6nSdbBo7s4rumI+vYBiPwFXmchWtKCgVNZREtf3ratF/6QU2WQ9UbXRTfcCCAVNDM+Zq42JeUIOnbSK+p9XR0K18KDL0heiHnv9W56cY=
    waf: AgA7CjkBQsAHP5VCOJkTkVdrluMENzz/3ZefJE/YEGQEcg5WOtMCiBATllkwsRvqU7+UTZZXPTcn5PVToWYunq3xsj28pII+nUI2XDeShbm2KTZS08Rk5miswsI9c0wZB0xqYIHS8OaM+QYeB4Vka3kmH6pk3DjrqrujYIla2ixqiGXU90nrdYtQ0GLFXIKNGDbdjtcKcZuksmpBOCjl9X+FbbMBgw5Gth/rRktjoZTKiPrQf7HXnCPddiQwowgMY9ucxDW9QVt/v2/uNwdGXNN4n0Mk6qRdCgwVuG9k1rwylYub3PpW03DsDDMyTv9WT1xX+WRP+0AdrGiGHCbDgoT/wpfGIwvYxcPg/d9noRhQpDN7COqOczJixcF9bYhaqXVOmGBD4ntKF43/2Upm5WllWoRJt3LMIcZ6i06PzM/T4lLcfpYwPW88pnrIz7e3J5ue67meo9TciEl4+OkqCqPJwy2dGwvCSaUQUskaXEzvBctkAqI1X9d5XD6/sBb4E9F2m6OPkO7+4UVakO0ho6gBIfSN8S9zU2bs1ZM9vsj1XLSzrVshuUdCNGSQT/e7pS3S9J2HPdP7zoPSMrO98zF5i33pOrtg14EICE/T4EfWOeSPH84hswC2VwOg5ZB/b3/ZFUHaBGsr1gNtCEPMOAhr4at0LSe0LlwDkiPmo2T+tQdpoYJblVn1jd2mhkSKQB8CXpMGvcZmv7Dp9E76ZD+rcQA4bEiswRPYSycuv0LFngHP1UjEy6Sux7t6TpmRZH0=
  template:
    metadata:
      name: bypass-tokens
      namespace: games-production
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-webhook
  namespace: games-production
spec:
  encryptedData:
    secret-token: AgA7DTHrdjDO/MAufgzz2bwyxJXtCwwLjW5bPxkie1+n5QYUmRhxbjnNLUdF64TFO7a6XV8WCUqFNqZYdJ6usY7xUjbYsCOOSSE7q0VpnrdIcnDKvVO1/xhI6V3WnovUaPOJxCP7kS5e1qmXYHXeyXSidLJp4NGDr5QuHNJRIxDiLBlmT+C9EU9mBbdYqtbUowjjEfuCFAi3t4aJ3pcCTvaYiN8xFjw75wm+DED62JgtVdeOLLaNR5QkC/mZ6TNC/lUjpwRW3VMkAM5Kk79pYEI/1h7psSsA02zXXm6RXT9SNHhelFsJUHNcJ9LWwxgsYfBnzw7K6aF95lDScSrVb4JzzO0VR3Xt2EibqIWL1dxdgk3i/l9eJDx9P798Kv0+IbmZ2wV3JEAw0UH5Q5V9YO0dlNIJI5lerYHWL31Tcoubd4HeEzm9QQhsWAkgimuzQi0RjrbyfnCpGy7oJi8Z4z6FIxlNEAzukiCwaOWHA5D8zPAHrGBCPgnL9n1DTLgShV2ikpLR3Y87teCOL0av2HXiAbjDtT3ATpv+YSHhbk5vzEibiqpVoNE7sw2fZTYv9PkVDv/ipI4l5N9w2fO599g7/NtDsoZezTgiE3ZGdXx2Fz7+orGeVQ9zQam6Dsmls/t6sXX3ZVBzFKptHhBevrCB/V95SK9Z5EJq37laPhrt1FRnEej2zH43Zlk7BeB9fxpMGDYCuJ16yQydW8r3zsOFSJGpJWuKJUZOOOYwSG90TmyuQMAGdt/iXDnYPV5QWX8=
  template:
    metadata:
      name: telegram-webhook
      namespace: games-production
    type: Opaque
