apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: arc-runners
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
