apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
  namespace: arc-runners
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi