apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: authentik-db
  namespace: authentik
spec:
  instances: 1
  postgres:
    version: '16.4'
  pods:
    persistentVolume:
      size: '2Gi'
  sgInstanceProfile: 'size-xs'
