apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-github
  namespace: oauth2-proxy
spec:
  encryptedData:
    client-id: AgAgkhadrXQ2a+aXVNevuxnBkv+Ms7RbL86eWGrxdWXyr40FI+kzJRuEcQIQE1ikoEUKGln1STHfGlcsvxPpUVbP124C6CG0J43wO2RvPXnCPxdXT9jzGAZJdxXlMHH3D9rREFbMaifDye8pTJ7f8LsKGqVrKCm2KO/wwdcDCBCfhkQCWw1HMGnuq5YnSiqlDJejyeppJ/CChpp6wIc1oXpALOWspzq8S0NWN98VLAiQXD047Vvp5UAqsZbWwKX2Z0a4yxnPG76v9ksVQ9dDM2HyItvdrBr6+pCJq0Oq27TyfZ0roltFcYxUlKg30GqrcoKWq+RbwChpP14Ol8Ln4hN0aQi1mu7dwyQ/3mEboabnsirHPPaRpZKhAtol9HRSwmqjDXcYTqLpEnbD5nvb+kml6vkT45fM8GVkhL/5UlLkXmG5dyHGjcgTbF0aeXubKgb7EJZzjTfaQzHB/NTNRlDqZSO0fuZ4wGg735aPHtWYJ8VAfoyfkD0DeUpmoLzWRCsyLHLgWRw3EPbaDj/ejbfgjkgX8yEXq988Sqc87oG1B5HsYHnPEXkCvHnyTBcfxQViumk1mcnUCZU10XH6kyD9iGWslaZo7dyNQ2jKjXzhC8h9bNQ1ZP5wvbj4su+h9Y+W9aatUlTw+nX1MyPzJNPclIU8OqIttqx4TOikG3fmYjvGPiTvEDVq4UMLSB0d5yHDtvJLQdmGHiQNMg/yf8mph/LjtQ==
    client-secret: AgB1CzXMB2tV9tzCy21fJPvdj6HK6di92lWLKN32Yc7vlcc77ipNFCgmo5sQ2R5Jq5ST9YBq9kgC3H03E9gc2MCpfeJsFoewrLkWETw3fDwuAtgZ7uZU0g2+ngzVcZ5Ztj+qcZ09+jvzSO9GoeCy13Y+B/jedYqnUzguDWjSSQamMmzsDGm/sRDU8wIkinVbjq3xyghwWUGuR0BilRHwMH+h56CqM8VVFdIYdN9brFNC9klkc6cKqEaEndCIKNUhMqqi+lJobyWpJq0QMmfU7eazuQzCKdfWSlsU2EniH5LmsEiH1KG9aEo4vexGm9KWgropOkwcj4F9++7iPCxbmXyC/RNpkgc4e9yki6AQuvVYeXkINmDlLQw44LqYW4GZal26FrIzO954oBkMA+SS4g/VGzHqs9Y22mZ76WZ++ka/0K+3E7zmEAd9P7JD9xAoqhZLZj1G/vrWp2AQJDSjfhKAj4O73zybyFA4PzlD4Gtzg3xtVkPxfuvZJ5cI5+KVsjTTgMmkLNdELGKS1d/yXOBELyF+fePDZ6+AtAacRmjpNSZkC3CpAY2QXb5++2lRKr3Sqj7YAb7TqH8QJJVtbHKAsjGzfuARo03zqpo2vmE8wkaT6AY+1vkw9EFCY0g8Gwf08C9nerYhaayAqWmdvNPp/c+PKLr9uAwbgvt8FBaQe39YPUOlfEM40zSU1eTqUw+FhySl2g5jbE6g5CWO2kLvkKKanhXtwJu49bISRbXvIfHW+zxduBFa
    cookie-secret: AgBJcQytn+aGUJLTIalP9nv7CBG60waGNApIeKDY4H/xOm8+2cCdLy914xuMY2I985lJ9fYvloiN5GVwADPFlAcpKoCm2e01FQt4i+A6DgN83Yhx/XaSC64WRfV1eDreof8BDo0imFXX2+YHF7rfFXWI/heo7dHIxWhIP+4JelG0rV+KcJlqIY1uC/wpQDv+314FVz9vhsyeYvxZO13X7KStMRnhx4fFUw3FmadqD59U/WYLEEz0iGnH21b1Is4B9uk1sjt6mdCaE3R9xSwK1+TLAx0i5Q72Ahx8T0O6Scg7/gQekX5sBJNuz3Jk6P98KWRIY+wv6GueEnSTY+4oXYGM/Vy+gHdWtJ+mqzHI82Ef8QSPcuVUPhPHKkfl8ddjqaY4OWDBBNunOFhCA4t31uWJh/62BIM42Ihpwynp0d3BZj/ty1hWf4fjEn9looxyAlDUWAUkbghhI90wT9pmKSwV0b/n6yDSBPS800bDwkp7MBKk/lFUXYWq+BhyUjIHHNRUbwtsEfeDl8JpNzJu8fc4HmzAA+6kn1XBefEBm6ABM9skVCMM1T7wBtoJOmvw8FoTxpersBkvQvo5lI2G/BVBeA3uMe5FzyEtYykgCETK+XpvpvKyJ1xDn/A8TXvr2GW1AuH4P8G9eQGKB7ComAzUsnCVc03FI3F4pElWa3JNB/W2atiDpbaQSTCqldR30l2leO2O3r9oC+ne9IeC+vt+PuBTafdP+Y87gAJWWFC/HpU+EcbAjbngied1bWzwP+q+9g==
  template:
    metadata:
      name: oauth2-proxy-github
      namespace: oauth2-proxy
    type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.7.26"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 10m
  values:
    config:
      cookieName: sso
      existingSecret: oauth2-proxy-github

    extraArgs:
      provider: github
      github-org: sigma-gaming
      cookie-domain: .sigmacloud.app
      whitelist-domain: .sigmacloud.app
      reverse-proxy: true
      skip-auth-preflight: true
      skip-auth-strip-headers: false

    ingress:
      enabled: true
      path: /
      hosts:
        - auth.sigmacloud.app
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
            - auth.sigmacloud.app
          secretName: sigmacloud.app-cloudflare-cert
