apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.7.26"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 10m
  values:
    config:
      cookieName: sso
      existingSecret: oauth2-proxy-github

    extraArgs:
      provider: github
      github-org: sigma-gaming
      cookie-domain: .sigmacloud.app
      whitelist-domain: .sigmacloud.app
      reverse-proxy: true
      skip-auth-preflight: true
      skip-auth-strip-headers: false

    ingress:
      enabled: true
      path: /
      hosts:
        - auth.sigmacloud.app
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
            - auth.sigmacloud.app
          secretName: sigmacloud.app-cloudflare-tls
