apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: flux-system
spec:
  interval: 1h
  url: https://oauth2-proxy.github.io/manifests
---
apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-proxy-github
  namespace: oauth2-proxy
spec:
  encryptedData:
    client-id: AgCUYe2zBA3fOEfOfr6yZTCqtfgolxeOUB9K349Jjf9JvJw7PLXkwmsJ1koh3zQF7RjYJYFyHR1CcNPLk2Fd7G4mGe0E2JAw4nF8DWZUmEj7ffAFIjBEpZm+TXkJhlMtv5ncGIJiSiPHoKVpF42uD1zdW7zj2zJ2RZi24LqLIpvuyAR2l3H/aTb+v2by+rxgA6GKyv6EUGXaQjRKHopHIRzBrmRxb4LLxgaOO9jFui0YE+hyEfwb7VSBHVFzXbfXwGgvcZ+2BZdUssBUC4ALvUtuqFZejp28V0yj4yLE5ipQPqsqsHsScMGW8z42vPFzQIwvXk+CkJW9Nf7wFKVFHwP08ByPRouCm0yoyRKmIyMSTVDZWW/cnV7WWeTHFLMBbDfmVWZ02CXyYt3ZsYb3WuFhDcNDfFPbYJ11RjhknQJoJJ2UEPXyhipu0dFBOCR7/m5UcIREhmF3+WOARdRmglRnHExJ+tRe/lPhiJF0oeJiFlSRWrur7f4deD0u9fHEYigYvh4+wmARqKS/pCjDqFEBFM3FVXnefeS0aMYwG0dkceC277ayvoPIRUrX2NXP9o3k9Gn2i3nhLPnKTw+jK83YzUh3ouhgwdtR/ARLewsLlkbnLzwg7OTxAomZiTypbzs7rAB5RojIWtib8wmeLAfYs8PuU18fiD0C0uK9pHDatTT436hxdpH0xSep1QuuU8IKez9xyrawre5LCFet1+xQPbTLbA==
    client-secret: AgANNmCqJbvjUHCdUojKUOZXz2JBF9Qo6Fuw2S+izJzghQv++S8gP5LB2mTAyZGjPKm31u1D9PwVLTwjmsoedgZu6DHLtSMn/QjyPyT5YJsoeNeO7AA6CJr0R3Iz05xeLjfws9l8xKZuyvaPfq1RyuXbXCHx44QUAbNdTaFYHXL0JrRF7fb91kaV4mGkODlS/p7COxFz9l/zPrpdFl9xYAIUyJchS9qNCfJ9yZE6TXONsklWhD5l2cN9kwnAuClEr1uVmmSDugfpJCpwNLBInZ4Y4KzN8ZIK+BIpxMDHek1BnDzu1JT5mOaEQ1TIlHJ9zPzQZvv+f8P+r8Ax7Y7xle//I69CdCeOUX+xlCejAJt1y45X7pZcx5BI4o0v4qkmYrqeMCiqEZgZ/QOw4IvjBQfnVXVbqExA8HXhx9OROt8PeEWLzQ39Ge8dCcexyjllLz8Dqy/IrBfrhMCzJuIhc+MkP2teE1ggJNy03vgOgzmE4TIedut669ppDW9uH47LVtWaizHEqaMnPXRnzbrgK4PlpsKRI+SAbvN/5cG8G5H2/O201DdKjEKjqpYDF1tQQBR0Jx2Zq3a44z7Bgz7xJIfO+FxEmmlEyFaB9KRjFTBiorhUWs9DjFnJghi9p93AbiGChznLnVbsSY/RhIyZT4vFhUrxv5DF/d9ZbPqTjZ5WC0IboCh4SEgKGTfAw83WXlEaqDluxDFqShlzSRh50PuqrIV68S4PMJqgR0idSEe2EsrNuvDF3ezA
    cookie-secret: AgBIXA0MZMook6YJTHgInspfKjc/johl0VV8PedBQJ+qW5JyiZNow4igt9VAWLYta0JAlDbzX7nFyEarqzasOrnbZ8XO5l0lCrCOL7BY4hLwLw15Ny8ixOJhppAU+YZEI04wQ//ZMUdOgKWFcJrSRaqHLHUQrQ7Ua7xq2Djk2/0SbSxx7AKu1xE+982nxMuEDs+jY2jNP73h4CydVe0RDtRkTZ1CLGH53NyFVcF2HNWKfs/PZVAo5PSLI/Y4iup8f4yt/wRdK3udj6q8q+z4anfCofK21xlLLh5aaYakC0/FuYAqEVsRIY/LVSLQAjbdraFB0wfbfvR0dQjZR9oU6seuZXPuZGozXnJdUhY8hvWdnDbCutyoaDyZRywpr64tRVRAQAH3mEYvSE4/glloI7EM0KhAj4JTGtgxwvZEuD0roYXXnK/l03/3Z+Cx20aAVTJglG5UkmxTihfib8qYJKzHQ08facScCilA2ida1iW28pOV431aeuhdy8ZwXqv81oZpXXxVEHHqG3HJJ5W7Wn8KoqZi3iWqsAUGtpPlpEiZj3EMcAFN/GEIkWUsIJH6puOLfWNb1DwyIOvKPGSIyOjETYzseHwYHjRZIGQVXBcdrSkZA2xwfHVk/C0JBpxGu11xFe7iwSi8G5jB9dpxv7B1bu1Ot405tictFkZhTUPmPQIoUlr65yjcFxUZE8MnhzOjHm8kZWPb8dzoxpjIc2T2qbm6oOOUbijN7Ef6oqTqSA==
  template:
    metadata:
      name: oauth2-proxy-github
      namespace: oauth2-proxy
    type: Opaque
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sigmacloud.app-cloudflare-tls
  namespace: oauth2-proxy
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: cloudflare-tls-store
  target:
    name: sigmacloud.app-cloudflare-tls
    template:
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: sigmacloud.app-cloudflare-tls
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: oauth2-proxy
      version: "7.7.26"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
        namespace: flux-system
      interval: 10m
  values:
    config:
      cookieName: sso
      existingSecret: oauth2-proxy-github

    extraArgs:
      provider: github
      github-org: sigma-gaming
      cookie-domain: .sigmacloud.app
      whitelist-domain: .sigmacloud.app
      reverse-proxy: true
      skip-auth-preflight: true
      skip-auth-strip-headers: false

    ingress:
      enabled: true
      path: /
      hosts:
        - auth.sigmacloud.app
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - hosts:
            - auth.sigmacloud.app
          secretName: sigmacloud.app-cloudflare-tls
