apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: google-creds-mirror
  namespace: google-creds
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/secret-mirror
      version: "1.0.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    targets:
      - namespace: games-production
        secrets:
          - production-backups-creds
