apiVersion: apps/v1
kind: Deployment
metadata:
  name: games-ws
  namespace: games-dev
  labels:
    app: games-ws
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: games-ws
  template:
    metadata:
      namespace: games-dev
      labels:
        app: games-ws
    spec:
      imagePullSecrets:
        - name: google-registry-creds
      containers:
        - name: games-ws
          image: europe-west4-docker.pkg.dev/sigma-games/docker/apis/games-ws:dev-1719901432293 # {"$imagepolicy": "games-dev:games-ws"}
          ports:
            - containerPort: 5052
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
          env:
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_DOMAIN
              value: "sigmacloud.app"
            - name: PUBLIC_GAMES_APP_URL
              value: "https://sigmacloud.app"
            - name: PUBLIC_GAMES_API_URL
              value: "https://api.sigmacloud.app"
            - name: PUBLIC_GAMES_WS_URL
              value: "https://ws.sigmacloud.app"
            - name: PUBLIC_GAMES_WS_VERSION
              value: "dev-1719901432293" # {"$imagepolicy": "games-dev:games-ws:tag"}
            - name: PUBLIC_CONTROL_APP_URL
              value: "https://control.sigmacloud.app"
            - name: PUBLIC_CONTROL_API_URL
              value: "https://control-api.sigmacloud.app"
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: games-db-app
                  key: uri
            - name: REDIS_HOST
              value: "redis-master"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-password
                  key: password
            - name: JWT_SECRET
              value: "SECRET_REMOVED"
            - name: PUBLIC_TELEGRAM_BOT_ID
              value: "6551119896"
            - name: TELEGRAM_BOT_TOKEN
              value: "SECRET_REMOVED"
            - name: PUBLIC_VK_APP_ID
              value: "51812041"
            - name: VK_APP_SECRET
              value: "SECRET_REMOVED"
            - name: VK_SERVICE_TOKEN
              value: "SECRET_REMOVED"
---
apiVersion: v1
kind: Service
metadata:
  name: games-ws
  namespace: games-dev
spec:
  selector:
    app: games-ws
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5052
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: games-ws
  namespace: games-dev
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ws.sigmacloud.app
      secretName: ws.sigmacloud.app-cert
  rules:
    - host: ws.sigmacloud.app
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: games-ws
                port:
                  number: 80
