apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-updates-common.yaml
  - 03-storage.yaml
  - games-app.yaml
  - games-app-updates.yaml
  - games-api.yaml
  - games-api-updates.yaml
  - games-ws.yaml
  - games-ws-updates.yaml
  - control-app.yaml
  - control-app-updates.yaml
  - control-api.yaml
  - control-api-updates.yaml
  - ./games-db-migration
  - games-db-migration-updates.yaml
