apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance-app
  namespace: games-dev
  labels:
    app: maintenance-app
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: maintenance-app
  template:
    metadata:
      namespace: games-dev
      labels:
        app: maintenance-app
    spec:
      imagePullSecrets:
        - name: google-registry-creds
      containers:
        - name: maintenance-app
          image: europe-west4-docker.pkg.dev/sigma-games/docker/apps/maintenance-app:dev-1725106355769 # {"$imagepolicy": "games-dev:maintenance-app"}
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthy
              port: 80
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
            initialDelaySeconds: 5
          resources:
            limits:
              cpu: "125m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance-app
  namespace: games-dev
spec:
  selector:
    app: maintenance-app
  ports:
    - protocol: TCP
      port: 80
