apiVersion: batch/v1
kind: Job
metadata:
  name: games-db-migration- # version is appended in kustomization.yaml
  namespace: games-stage
spec:
  ttlSecondsAfterFinished: 86400
  template:
    spec:
      imagePullSecrets:
        - name: google-registry-creds
      containers:
        - name: games-db-migration
          image: europe-west4-docker.pkg.dev/sigma-games/docker/migrations/games-db-migration:dev-1730329171177 # {"$imagepolicy": "games-stage:games-db-migration"}
          env:
            - name: NODE_ENV
              value: "production"
            - name: GAMES_DB_HOST
              value: "games-db-primary.games-stage"
            - name: GAMES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: games-db
                  key: superuser-username
            - name: GAMES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: games-db
                  key: superuser-password
      restartPolicy: Never
