apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: core-ws
  namespace: games-production
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/live-api
      version: "1.2.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
      remediateLastFailure: false
  upgrade:
    remediation:
      retries: -1
      remediateLastFailure: false
  values:
    name: core-ws
    replicaCount: 1
    nodeSelector:
      role: application
      environment: production
    image:
      repository: europe-west4-docker.pkg.dev/sigma-games/docker/core-ws
      tag: dev-1741868898691 # {"$imagepolicy": "games-production:core-ws:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      hosts:
        - ws.sigma1.games
      annotations:
        nginx.ingress.kubernetes.io/upstream-hash-by: "$cookie_sticky"
    metrics:
      enabled: true
    migration:
      tag: dev-1741837502636 # {"$imagepolicy": "games-production:core-migrations:tag"}
    env:
      - name: CoreDb__Host
        value: "core-db-pooler-rw"
      - name: CoreDb__Username
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: user
      - name: CoreDb__Password
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: password
      - name: CoreDb__Database
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: dbname
      - name: CoreCache__Host
        value: "core-dragonfly"
      - name: CoreCache__Password
        valueFrom:
          secretKeyRef:
            name: core-dragonfly-auth
            key: password
      - name: CoreCache__Version
        value: "dev-1741561454444" # {"$imagepolicy": "games-production:core-api:tag"}
      - name: CoreNats__Url
        value: "nats://core-nats:4222"
