apiVersion: v1
kind: Namespace
metadata:
  name: debug
  labels:
    pod-security.kubernetes.io/enforce: privileged
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: debug-host
  namespace: debug
spec:
  selector:
    matchLabels:
      app: debug-host
  template:
    metadata:
      labels:
        app: debug-host
    spec:
      hostNetwork: true
      priorityClassName: system-cluster-critical
      tolerations:
        - operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/memory-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/pid-pressure
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/unschedulable
          operator: Exists
          effect: NoSchedule
        - key: node.kubernetes.io/network-unavailable
          operator: Exists
          effect: NoSchedule
      containers:
        - name: netshoot
          image: nicolaka/netshoot:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
        - name: busybox
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            privileged: true
