apiVersion: v1
kind: Namespace
metadata:
  name: infisical-secrets-production
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-production
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /oauth2-proxy-github

  managedKubeSecretReferences:
    - secretName: oauth2-proxy-github
      secretNamespace: oauth2-proxy
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          client-id: "{{ .CLIENT_ID.Value }}"
          client-secret: "{{ .CLIENT_SECRET.Value }}"
          cookie-secret: "{{ .COOKIE_SECRET.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-production
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /games-dragonfly-auth

  managedKubeSecretReferences:
    - secretName: games-dragonfly-auth
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          password: "{{ .PASSWORD.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-production
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /telegram

  managedKubeSecretReferences:
    - secretName: telegram
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          bot-token: "{{ .BOT_TOKEN.Value }}"
          webhook-secret-token: "{{ .WEBHOOK_SECRET_TOKEN.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-production
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /vk

  managedKubeSecretReferences:
    - secretName: vk
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          app-secret: "{{ .APP_SECRET.Value }}"
          service-token: "{{ .SERVICE_TOKEN.Value }}"
          group-token: "{{ .GROUP_TOKEN.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-production
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /bypass-tokens

  managedKubeSecretReferences:
    - secretName: bypass-tokens
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        data:
          waf: "{{ .WAF.Value }}"
          rate-limit: "{{ .RATE_LIMIT.Value }}"
