apiVersion: v1
kind: Namespace
metadata:
  name: infisical-secrets-production
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-oauth2-proxy-github
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /oauth2-proxy-github

  managedKubeSecretReferences:
    - secretName: oauth2-proxy-github
      secretNamespace: oauth2-proxy
      creationPolicy: "Orphan"
      template:
        data:
          client-id: "{{ .CLIENT_ID.Value }}"
          client-secret: "{{ .CLIENT_SECRET.Value }}"
          cookie-secret: "{{ .COOKIE_SECRET.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-core-dragonfly-auth
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /core-dragonfly-auth

  managedKubeSecretReferences:
    - secretName: core-dragonfly-auth
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        data:
          password: "{{ .PASSWORD.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-telegram
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /telegram

  managedKubeSecretReferences:
    - secretName: telegram
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        data:
          bot-id: "{{ .BOT_ID.Value }}"
          bot-username: "{{ .BOT_USERNAME.Value }}"
          bot-token: "{{ .BOT_TOKEN.Value }}"
          webhook-secret-token: "{{ .WEBHOOK_SECRET_TOKEN.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-vk
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /vk

  managedKubeSecretReferences:
    - secretName: vk
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        data:
          app-secret: "{{ .APP_SECRET.Value }}"
          service-token: "{{ .SERVICE_TOKEN.Value }}"
          group-token: "{{ .GROUP_TOKEN.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-bypass-tokens
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /bypass-tokens

  managedKubeSecretReferences:
    - secretName: bypass-tokens
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        data:
          waf: "{{ .WAF.Value }}"
          rate-limit: "{{ .RATE_LIMIT.Value }}"
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisical-secrets-payment
  namespace: infisical-secrets-production
spec:
  hostAPI: https://eu.infisical.com/api
  resyncInterval: 10
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: infisical-service-token-production
        secretNamespace: infisical-system-secrets
      secretsScope:
        envSlug: prod
        secretsPath: /payment

  managedKubeSecretReferences:
    - secretName: payment
      secretNamespace: games-production
      creationPolicy: "Orphan"
      template:
        data:
          coincap-api-key: "{{ .COINCAP_API_KEY.Value }}"
          plisio-api-key: "{{ .PLISIO_API_KEY.Value }}"
          plisio-stale-deposit-timeout-minutes: "{{ .PLISIO_DEPOSIT_TIMEOUT_MINUTES.Value }}"
          plisio-stale-withdrawal-timeout-minutes: "{{ .PLISIO_WITHDRAWAL_TIMEOUT_MINUTES.Value }}"
          cryptocloud-api-key: "{{ .CRYPTOCLOUD_API_KEY.Value }}"
          cryptocloud-secret-key: "{{ .CRYPTOCLOUD_SECRET_KEY.Value }}"
          cryptocloud-stale-deposit-timeout-minutes: "{{ .CRYPTOCLOUD_DEPOSIT_TIMEOUT_MINUTES.Value }}"
          cryptocloud-stale-withdrawal-timeout-minutes: "{{ .CRYPTOCLOUD_WITHDRAWAL_TIMEOUT_MINUTES.Value }}"