{{- range $i, $job := .Values.jobs }}
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ $job.name | kebabcase }}
spec:
  schedule: "{{ $job.schedule }}"
  timeZone: "Europe/Moscow"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if $job.deadlineSeconds }}
          activeDeadlineSeconds: {{ $job.deadlineSeconds }}
          {{- else }}
          activeDeadlineSeconds: 60
          {{- end }}
          restartPolicy: OnFailure
          {{- if $.Values.nodeSelector }}
          nodeSelector:
            {{- toYaml $.Values.nodeSelector | nindent 12 }}
          {{- end }}
          imagePullSecrets:
            - name: google-registry-creds
          {{- if $.Values.migration.enabled }}
          initContainers:
            - name: wait-for-core-migrations
              image: ghcr.io/groundnuty/k8s-wait-for:v1.6
              args:
                - "job"
                - "core-migrations-$(GAMES_DB_MIGRATION_TAG)"
              env:
                - name: GAMES_DB_MIGRATION_TAG
                  value: {{ $.Values.migration.tag }}
          {{- end }}
          containers:
            - name: {{ $job.name | kebabcase }}
              image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
              resources:
                {{- toYaml $.Values.resources | nindent 16 }}
              env:
                {{- toYaml $.Values.env | nindent 16 }}
                - name: "{{ $.Values.jobEnvName }}"
                  value: "{{ $job.name }}"
---
{{- end }}