apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: referral-redirect-api
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.2.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: referral-redirect-api
    replicaCount: 1
    image:
      repository: europe-west4-docker.pkg.dev/sigma-games/docker/apis/referral-redirect-api
      tag: dev-1730239062961 # {"$imagepolicy": "games-stage:referral-redirect-api:tag"}
    ingress:
      host: sigm.to
    service:
      port: 5054
    migration:
      tag: dev-1730235782634 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1730238554196" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: PUBLIC_REFERRAL_REDIRECT_API_URL
        value: "https://sigm.to"
      - name: PUBLIC_REFERRAL_REDIRECT_API_VERSION
        value: "dev-1730239062961" # {"$imagepolicy": "games-stage:referral-redirect-api:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-primary.games-stage"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db
            key: superuser-username
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db
            key: superuser-password
      - name: GAMES_REDIS_HOST
        value: "games-dragonfly"
      - name: GAMES_REDIS_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
