apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: referral-redirect-api
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.6.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: referral-redirect-api
    replicaCount: 1
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apis/referral-redirect-api
      tag: dev-1734722834026 # {"$imagepolicy": "games-stage:referral-redirect-api:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      hosts:
        - sigm.to
    migration:
      tag: dev-1734649464037 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: REFERRAL_REDIRECT_API_PORT
        value: "8080"
      - name: REFERRAL_REDIRECT_API_INTERNAL_PORT
        value: "9090"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1734722834026" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: PUBLIC_REFERRAL_REDIRECT_API_URL
        value: "https://sigm.to"
      - name: PUBLIC_REFERRAL_REDIRECT_API_VERSION
        value: "dev-1734722834026" # {"$imagepolicy": "games-stage:referral-redirect-api:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-pooler-rw"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: user
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: password
      - name: GAMES_DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: dbname
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
