apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 01-namespace.yaml
  - 02-roles.yaml
  - 03-updates-common.yaml
  - 04-storage.yaml
  - ./games-db-migration
  - games-db-migration-updates.yaml
  - maintenance-app.yaml
  - maintenance-app-updates.yaml
  - hr-games-app.yaml
  - hr-games-api.yaml
  - hr-games-ws.yaml
  - hr-games-tasks.yaml
  - hr-referral-redirect-api.yaml
  - hr-control-app.yaml
  - hr-control-api.yaml
