apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: letsauth
  namespace: games-production
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/live-api
      version: "1.0.2"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: letsauth
    replicaCount: 1
    nodeSelector:
      role: application
      environment: production
    image:
      repository: europe-west4-docker.pkg.dev/sigma-games/docker/apis/letsauth
      tag: dev-1736721752855 # {"$imagepolicy": "games-production:letsauth:tag"}
    ports:
      public: 8080
    healthchecks:
      port: public
    ingress:
      hosts:
        - letsauth.app
    migration:
      tag: dev-1736632711733 # {"$imagepolicy": "games-production:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: PORT
        value: "8080"
      - name: PUBLIC_AUTH_API_DOMAIN
        value: "letsauth.app"
      - name: PUBLIC_AUTH_API_URL
        value: "https://letsauth.app"
      - name: PUBLIC_AUTH_API_VERSION
        value: "dev-1736721752855" # {"$imagepolicy": "games-production:letsauth:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-pooler-rw"
      - name: GAMES_DB_HEALTH_HOST
        value: "games-db-health-pooler-rw"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: user
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: password
      - name: GAMES_DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: dbname
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
      - name: PUBLIC_TELEGRAM_BOT_ID
        valueFrom:
          configMapKeyRef:
            name: telegram
            key: bot-id
      - name: TELEGRAM_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegram
            key: bot-token
      - name: PUBLIC_VK_APP_ID
        value: "12345"
      - name: VK_SERVICE_TOKEN
        value: "12345"
