apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics-datasource-prometheus
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: prometheus
    name: VictoriaMetrics
    url: http://vmsingle-victoria-metrics-k8s-stack:8429
    isDefault: true
  instanceSelector:
    matchLabels:
      dashboards: grafana
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics-datasource
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: victoriametrics-datasource
    name: VictoriaMetrics (DS)
    url: http://vmsingle-victoria-metrics-k8s-stack:8429
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.3/victoriametrics-datasource-v0.10.3.zip;victoriametrics-datasource
      version: 0.10.3
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics-logs-datasource
  namespace: monitoring
spec:
  datasource:
    access: proxy
    type: victoriametrics-logs-datasource
    name: VictoriaLogs
    url: http://victoria-logs-victoria-logs-single-server:8428
  instanceSelector:
    matchLabels:
      dashboards: grafana
  plugins:
    - name: https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.13.0/victoriametrics-logs-datasource-v0.13.0.zip;victoriametrics-logs-datasource
      version: 0.13.0