apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  interval: 1m
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 10m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    victoria-metrics-operator:
      nodeSelector:
        role: monitoring
      crds:
        enabled: false # installed separately with crds.yaml
        plain: false
      admissionWebhooks:
        certManager:
          enabled: true
    vmsingle:
      spec:
        nodeSelector:
          role: monitoring
    alertmanager:
      spec:
        nodeSelector:
          role: monitoring
    vmalert:
      spec:
        nodeSelector:
          role: monitoring
    kube-state-metrics:
      image:
        registry: docker.io
        repository: bitnami/kube-state-metrics
        tag: "2.14.0"
    kubeApiServer:
      enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    kubeControllerManager:
      enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    kubeEtcd:
      enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    kubeScheduler:
      enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    grafana:
      nodeSelector:
        role: monitoring

      plugins:
      - "https://github.com/VictoriaMetrics/victoriametrics-datasource/releases/download/v0.10.3/victoriametrics-datasource-v0.10.3.zip;victoriametrics-datasource"
      - "https://github.com/VictoriaMetrics/victorialogs-datasource/releases/download/v0.12.0/victorialogs-datasource-v0.12.0.zip;victorialogs-datasource"

      grafana.ini:
        plugins:
          allow_loading_unsigned_plugins: victoriametrics-datasource,victorialogs-datasource

      defaultDatasourceType: "prometheus"

      sidecar:
        datasources:
          enabled: true
          # -- List of default prometheus compatible datasource configurations.
          # VM `url` will be added to each of them in templates and `type` will be set to defaultDatasourceType if not defined
          default:
            - name: VictoriaMetrics
              isDefault: true
            - name: VictoriaMetrics (DS)
              isDefault: false
              type: victoriametrics-datasource
          initDatasources: true
          createVMReplicasDatasources: false
          searchNamespace: ALL

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: VictoriaLogs
            type: victorialogs-datasource
            access: proxy
            url: http://victoria-logs-victoria-logs-single-server.monitoring.svc.cluster.local:9428

      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: selfsigned
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          nginx.ingress.kubernetes.io/proxy-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
          nginx.ingress.kubernetes.io/auth-url: https://auth.sigmacloud.app/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: https://auth.sigmacloud.app/oauth2/start?rd=$scheme://$host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-snippet: |
            if ($request_method = OPTIONS) {
              return 200;
            }
        hosts:
          - grafana.sigmacloud.app
        tls:
          - hosts:
              - grafana.sigmacloud.app
            secretName: grafana.sigmacloud.app-cert
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.8.11"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 10m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    server:
      nodeSelector:
        role: monitoring
      persistentVolume:
        enabled: true
    vector:
      enabled: true
    dashboards:
      enabled: true