{
 "title": "Games API Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(games_api_bets_amount, namespace)"
   },
   {
    "name": "game",
    "label": "Game",
    "query": "label_values(games_api_bets_amount, game)"
   }
  ]
 },
 "panels": [
  {
   "title": "Amount of Bets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(games_api_bets_amount{namespace=~\"$namespace\",game=~\"$game\"}) / 100",
     "legendFormat": "Bets ({{game}})"
    }
   ]
  },
  {
   "title": "Amount of Wins",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(games_api_wins_amount{namespace=~\"$namespace\",game=~\"$game\"}) / 100",
     "legendFormat": "Wins ({{game}})"
    }
   ]
  },
  {
   "title": "Amount of Losses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(games_api_losses_amount{namespace=~\"$namespace\",game=~\"$game\"}) / 100",
     "legendFormat": "Losses ({{game}})"
    }
   ]
  },
  {
   "title": "Dice Sides Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(games_api_dice_sides_bucket{le=\"1\", namespace=~\"$namespace\"}[$__interval])",
     "legendFormat": "1 side"
    },
    {
     "expr": "sum by () (increase(games_api_dice_sides_bucket{le=\"2\", namespace=~\"$namespace\"}[$__interval])) - sum by () (increase(games_api_dice_sides_bucket{le=\"1\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "2 sides"
    },
    {
     "expr": "sum by () (increase(games_api_dice_sides_bucket{le=\"3\", namespace=~\"$namespace\"}[$__interval])) - sum by () (increase(games_api_dice_sides_bucket{le=\"1\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "3 sides"
    },
    {
     "expr": "sum by () (increase(games_api_dice_sides_bucket{le=\"4\", namespace=~\"$namespace\"}[$__interval])) - sum by () (increase(games_api_dice_sides_bucket{le=\"1\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "4 sides"
    },
    {
     "expr": "sum by () (increase(games_api_dice_sides_bucket{le=\"5\", namespace=~\"$namespace\"}[$__interval])) - sum by () (increase(games_api_dice_sides_bucket{le=\"1\", namespace=~\"$namespace\"}[$__interval]))",
     "legendFormat": "5 sides"
    }
   ]
  }
 ]
}