{
 "title": "Node.js",
 "description": "Monitor an application built using Node.js",
 "tags": [ "nodejs-integration" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(nodejs_eventloop_lag_seconds, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(nodejs_eventloop_lag_seconds, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Node.js Version",
   "type": "stat",
   "description": "The version of Node.js.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Node.js Restarts",
   "type": "stat",
   "description": "The number of times Node.js restarted.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=~\"$job\", instance=~\"$instance\", hostname=~\"$hostname\"}[$__range]))",
     "legendFormat": "Node.js"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "System CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval]) * 100",
     "legendFormat": "Total CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Time Spent",
   "type": "timeseries",
   "description": "CPU time spent.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Active Handlers and Requests",
   "type": "timeseries",
   "description": "Number of active handle and active requests.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Handler - {{instance}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Active Request - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Latency",
   "type": "timeseries",
   "description": "Latency of the event loop.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Last - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P99 - {{instance}}"
    },
    {
     "expr": "nodejs_eventloop_lag_p50_seconds{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "P50 - {{instance}}"
    }
   ]
  },
  {
   "title": "Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Duration Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection duration.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "description": "Duration of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "Usage of heap memory.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Used - {{instance}}"
    },
    {
     "expr": "process_resident_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "Resident - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "External - {{instance}}"
    }
   ]
  },
  {
   "title": "GC Rate",
   "type": "timeseries",
   "description": "Rate of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}} - {{kind}}"
    }
   ]
  },
  {
   "title": "GC Count",
   "type": "timeseries",
   "description": "Count of garbage collection.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{kind}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Heap Space Used",
   "type": "timeseries",
   "description": "Usage of heap space.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{space}} - {{instance}}"
    }
   ]
  }
 ]
}