apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: elastic-stack
spec:
  version: 8.13.4

  nodeSets:
    - name: default
      count: 1
      podTemplate:
        spec:
          nodeSelector:
            monitoring: "true"
