apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  version: 8.13.4

  http:
    tls:
      selfSignedCertificate:
        disabled: true

  count: 1

  podTemplate:
    spec:
      nodeSelector:
        monitoring: "true"

  elasticsearchRef:
    name: "elasticsearch"

  config:
    server.publicBaseUrl: "https://kibana.rcbot.app"
    xpack.fleet.agents.elasticsearch.hosts:
      ["https://elasticsearch-es-http.elastic-stack.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts:
      ["https://fleet-server-agent-http.elastic-stack.svc:8220"]

    xpack.fleet.packages:
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest

    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: fleet-server-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
      - name: Elastic Agent on ECK policy
        id: elastic-agent-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
            inputs:
              system-logfile:
                enabled: false
              system-winlog:
                enabled: false
              system-httpjson:
                enabled: false
              system-system/metrics:
                enabled: true
                streams:
                  system.core:
                    enabled: true
                    vars:
                      period: 10s
                      core.metrics:
                      - percentages
                  system.cpu:
                    enabled: true
                    vars:
                      period: 10s
                      cpu.metrics:
                      - percentages
                      - normalized_percentages
                  system.diskio:
                    enabled: true
                    vars:
                      period: 10s
                      diskio.include_devices: []
                  system.filesystem:
                    enabled: true
                    vars:
                      period: 1m
                      filesystem.ignore_types: []
                      processors: |
                        - drop_event.when.regexp:
                            system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
                  system.fsstat:
                    enabled: true
                    vars:
                      period: 1m
                      processors: |
                        - drop_event.when.regexp:
                            system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
                  system.load:
                    enabled: true
                    vars:
                      period: 10s
                  system.memory:
                    enabled: true
                    vars:
                      period: 10s
                  system.network:
                    enabled: true
                    vars:
                      period: 10s
                      network.interfaces: []
                  system.process:
                    enabled: true
                    vars:
                      period: 10s
                      process.include_top_n.by_cpu: 5
                      process.include_top_n.by_memory: 5
                      process.cmdline.cache.enabled: true
                      process.cgroups.enabled: false
                      process.env.whitelist: []
                      process.include_cpu_ticks: false
                      processes:
                      - ".*"
                  system.process.summary:
                    enabled: true
                    vars:
                      period: 10s
                  system.socket_summary:
                    enabled: true
                    vars:
                      period: 10s
                  system.uptime:
                    enabled: true
                    vars:
                      period: 10s