apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-stack
spec:
  version: 8.13.4

  http:
    tls:
      selfSignedCertificate:
        disabled: true

  count: 1

  podTemplate:
    spec:
      nodeSelector:
        monitoring: "true"

  elasticsearchRef:
    name: "elasticsearch"

  config:
    server.publicBaseUrl: "https://kibana.rcbot.app"
    xpack.fleet.agents.elasticsearch.hosts:
      ["https://elasticsearch-es-http.elastic-stack.svc:9200"]
    xpack.fleet.agents.fleet_server.hosts:
      ["https://fleet-server-agent-http.elastic-stack.svc:8220"]

    xpack.fleet.packages:
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
      - name: system
        version: latest

    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: fleet-server-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
      - name: Elastic Agent on ECK policy
        id: elastic-agent-policy
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system
            inputs:
              - id: system-1/metrics-system
                type: system/metrics
                streams:
                  - id: system-1/metrics-system/core
                    data_stream:
                      dataset: system.core
                      type: metrics
                    metricsets:
                      - core
                    core.metrics:
                      - percentages
                  - id: system-1/metrics-system/cpu
                    data_stream:
                      dataset: system.cpu
                      type: metrics
                    metricsets:
                      - cpu
                    cpu.metrics:
                      - percentages
                      - normalized_percentages
                    period: 10s
                  - id: system-1/metrics-system/diskio
                    data_stream:
                      dataset: system.diskio
                      type: metrics
                    metricsets:
                      - diskio
                    diskio.include_devices: null
                    period: 10s
                  - id: system-1/metrics-system/filesystem
                    data_stream:
                      dataset: system.filesystem
                      type: metrics
                    metricsets:
                      - filesystem
                    period: 1m
                    processors:
                      - drop_event.when.regexp:
                          system.filesystem.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
                  - id: system-1/metrics-system/fsstat
                    data_stream:
                      dataset: system.fsstat
                      type: metrics
                    metricsets:
                      - fsstat
                    period: 1m
                    processors:
                      - drop_event.when.regexp:
                          system.fsstat.mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
                  - id: system-1/metrics-system/load
                    data_stream:
                      dataset: system.load
                      type: metrics
                    metricsets:
                      - load
                    condition: '${host.platform} != ''windows'''
                    period: 10s
                  - id: system-1/metrics-system/memory
                    data_stream:
                      dataset: system.memory
                      type: metrics
                    metricsets:
                      - memory
                    period: 10s
                  - id: system-1/metrics-system/network
                    data_stream:
                      dataset: system.network
                      type: metrics
                    metricsets:
                      - network
                    period: 10s
                    network.interfaces: null
                  - id: system-1/metrics-system/process
                    data_stream:
                      dataset: system.process
                      type: metrics
                    metricsets:
                      - process
                    period: 10s
                    process.include_top_n.by_cpu: 5
                    process.include_top_n.by_memory: 5
                    process.cmdline.cache.enabled: true
                    process.cgroups.enabled: false
                    process.include_cpu_ticks: false
                    processes:
                      - .*
                  - id: system-1/metrics-system/process.summary
                    data_stream:
                      dataset: system.process.summary
                      type: metrics
                    metricsets:
                      - process_summary
                    period: 10s
                  - id: system-1/metrics-system/system
                    data_stream:
                      dataset: system.socket_summary
                      type: metrics
                    metricsets:
                      - socket_summary
                    period: 10s
                  - id: system-1/metrics-system/uptime
                    data_stream:
                      dataset: system.uptime
                      type: metrics
                    metricsets:
                      - uptime
                    period: 10s