apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: games-db-migration
  namespace: games-production
spec:
  image: europe-west4-docker.pkg.dev/sigma-games/docker/migrations/games-db-migration
  secretRef:
    name: google-registry-creds
  interval: 30s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: games-db-migration
  namespace: games-production
spec:
  imageRepositoryRef:
    name: games-db-migration
  filterTags:
    pattern: "^dev-(?P<timestamp>.*)"
    extract: "$timestamp"
  policy:
    numerical:
      order: asc
