apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-db
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/stage/authentik/db.yaml
  prune: true
  dependsOn:
  - name: stackgres
  - name: authentik-shared
  sourceRef:
    kind: GitRepository
    name: flux-system
