apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: authentik-nginx
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./cluster-components/stage/authentik/nginx
  prune: true
  dependsOn:
  - name: ingress-nginx
  - name: authentik
  sourceRef:
    kind: GitRepository
    name: flux-system
  