apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: games-db
  namespace: games-dev
spec:
  instances: 1

  storage:
    size: 10Gi
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.bitnami.com/bitnami
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-password
  namespace: games-dev
spec:
  encryptedData:
    password: AgCC4plgvTuc9R6g/piLT/ba+xCIsmXksKVe5izVwUt4Q9DKwGVnj+VtSSL5/kGpnVpPkBKEOPK80WwEHbsykKfma8pbAx56oE8RMZQK9wvJ1/KkJs6BTYy1D5Y6vXL+U1X4gzrPx6VfdfKIHeJ0rH+j87kpOhiY0QMJRU4SsCb77ckJoe5MQ4uLVK0powYqV1Qm3gLErkjn6Shf9DFQMG9x1BJJtZjsd6BSTe6QFrIU14da8O3atwBz0ViiojO4+XJ8gKfjQ0DSf83rnU6pG3mPwgSgwCvEhGm5DEqGW0Vc7yRfvj/FySsiPTKBR9j3dDUq5wuEXFrajisuZj36jnCHn32GwERjVnvTGEUblEo2mqRvbT91flIjIBnBO7NmbnoALaXgy0H/qKQbnN76/cCovknlLuAJOls8VVOMtdnpG8Sd4tOTvJ7O9DUmZ51ZtiZtZuIzx3sY8HtjxFEYlOUCJ//4EDvyVVHxFRTJY+qv92ESnZWcFGHapDiLq/IS3hhSS3QZYNlqopXq1ZSYCrhpNhUgkHNoZyOr2bzaJAOfZp5ppnuA6RN4Mn7gDJVO+E9W72yOQc5AsBS2kDR5t0hHrhpQdZrU1aYEFwJ+csutd/uMA+PxcM7xhx6JTq7ROPUIgh+zSg8kFWuuRnYRBnH/3eDhTRxdPI+u5X1r0T8PLP35xQO6z4e/FRHmRr2BdHQuy2hPlTwfkPnu
  template:
    metadata:
      name: redis-password
      namespace: games-dev
    type: Opaque
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: games-dev
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: redis
      version: '19.6.0'
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      interval: 10m
  values:
    architecture: standalone
    auth:
      existingSecret: redis-password
      existingSecretPasswordKey: password
    replica:
      replicaCount: 1
