apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: games-app
  namespace: games-dev
spec:
  image: europe-west4-docker.pkg.dev/sigma-games/docker/apps/games-app
  secretRef:
    name: google-registry-creds
  interval: 30s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: games-app
  namespace: games-dev
spec:
  imageRepositoryRef:
    name: games-app
  filterTags:
    pattern: '^dev-(?P<timestamp>.*)'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: games-app
  namespace: games-dev
spec:
  interval: 30s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Changed.Changes}}{{print .OldValue}} -> {{println .NewValue}}{{end}}'
    push:
      branch: main
  update:
    path: ./stands/dev
    strategy: Setters