apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- 01-namespace.yaml
- 02-updates-common.yaml
- 03-storage.yaml
- 04-app.yaml
- 05-app-updates.yaml
- 06-api.yaml
- 07-api-updates.yaml
