apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: applications
  namespace: monitoring
spec:
  title: "Applications"
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
