apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - folders.yaml
  - dashboards/nodejs.yaml
  - dashboards/games-ws.yaml
  - dashboards/games-api.yaml

configMapGenerator:
  - name: games-api-dashboard
    namespace: monitoring
    files:
      - dashboards/games-api.json
