apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: maintenance-app
  namespace: games-stage
spec:
  image: europe-west1-docker.pkg.dev/sigma-games/docker/apps/maintenance-app
  secretRef:
    name: google-registry-creds
  interval: 30s
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: maintenance-app
  namespace: games-stage
spec:
  imageRepositoryRef:
    name: maintenance-app
  filterTags:
    pattern: '^dev-(?P<timestamp>.*)'
    extract: '$timestamp'
  policy:
    numerical:
      order: asc