apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: dragonfly
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Dragonfly"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: dragonfly
  namespace: monitoring
spec:
  folderRef: dragonfly
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  url: "https://raw.githubusercontent.com/dragonflydb/dragonfly-operator/refs/heads/main/monitoring/grafana-dashboard.json"
