apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: games-db
  namespace: games-production
spec:
  instances: 1
  imageName: risenx/cnpg-postgres-uuidv7:17.2-28

  enableSuperuserAccess: true

  affinity:
    nodeSelector:
      role: application
      environment: production

  storage:
    size: 20Gi

  resources:
    requests:
      cpu: "250m"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "4Gi"

  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "1GB"
      effective_cache_size: "3GB"
      work_mem: "4MB"
      max_slot_wal_keep_size: "1GB"
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all

  # bootstrap:
  #   recovery:
  #     source: games-db
  #   initdb:
  #     postInitTemplateSQL:
  #       - "CREATE EXTENSION pg_uuidv7;"

  # externalClusters:
  #   - name: games-db
  #     barmanObjectStore:
  #       destinationPath: gs://sigma-games-production-backups
  #       googleCredentials:
  #         applicationCredentials:
  #           name: production-backups-creds
  #           key: gcs-credentials
  #       wal:
  #         compression: snappy
  #         maxParallel: 8

  backup:
    retentionPolicy: "1d"
    barmanObjectStore:
      destinationPath: gs://sigma-games-production-backups
      googleCredentials:
        applicationCredentials:
          name: production-backups-creds
          key: gcs-credentials
      wal:
        compression: snappy
        maxParallel: 8
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: games-db-backup
  namespace: games-production
spec:
  schedule: "0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: games-db
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: games-db-pooler-rw
  namespace: games-production
spec:
  cluster:
    name: games-db

  type: rw

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "200"
      default_pool_size: "20"
      min_pool_size: "10"
      reserve_pool_size: "10"
      server_idle_timeout: "300"
      query_timeout: "15"

  template:
    spec:
      nodeSelector:
        role: application
        environment: production
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: games-db-health-pooler-rw
  namespace: games-production
spec:
  cluster:
    name: games-db

  type: rw

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "10"
      default_pool_size: "5"
      min_pool_size: "3"
      reserve_pool_size: "2"
      server_idle_timeout: "300"
      query_timeout: "5"

  template:
    spec:
      nodeSelector:
        role: application
        environment: production
      containers:
        - name: pgbouncer
          resources:
            requests:
              cpu: "0.1"
              memory: "64Mi"
            limits:
              cpu: "0.25"
              memory: "128Mi"
