apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: monitoring
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    plugins:
      allow_loading_unsigned_plugins: "victoriametrics-datasource,victoriametrics-logs-datasource"
  deployment:
    spec:
      template:
        spec:
          nodeSelector:
            role: service
  ingress:
    metadata:
      annotations:
        nginx.ingress.kubernetes.io/proxy-body-size: "0"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
        nginx.ingress.kubernetes.io/auth-url: https://auth.sigmacloud.app/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.sigmacloud.app/oauth2/start?rd=$scheme://$host$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-snippet: |
          if ($request_method = OPTIONS) {
            return 200;
          }
    spec:
      ingressClassName: nginx
      rules:
        - host: grafana.sigmacloud.app
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
      tls:
        - hosts:
            - grafana.sigmacloud.app
          secretName: sigmacloud.app-cloudflare-cert
