apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: control-app
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-app
      version: "0.3.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: control-app
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apps/control-app
      tag: dev-1735936051564 # {"$imagepolicy": "games-stage:control-app:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      hosts:
        - control.sigmacloud.app
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
        nginx.ingress.kubernetes.io/auth-url: https://auth.sigmacloud.app/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.sigmacloud.app/oauth2/start?rd=$scheme://$host$escaped_request_uri
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_STAGE
        value: "production"
      - name: PUBLIC_DOMAIN
        value: "sigmacloud.app"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_AUTH_API_URL
        value: "https://letsauth.app"
      - name: PUBLIC_GAMES_API_URL
        value: "https://api.sigma1.games"
      - name: PUBLIC_GAMES_WS_URL
        value: "wss://ws.sigma1.games"
      - name: PUBLIC_CONTROL_APP_URL
        value: "https://control.sigmacloud.app"
      - name: PUBLIC_CONTROL_APP_VERSION
        value: "dev-1735936051564" # {"$imagepolicy": "games-stage:control-app:tag"}
      - name: PUBLIC_CONTROL_API_URL
        value: "https://control-api.sigmacloud.app"
      - name: PUBLIC_ACCESS_API_URL
        value: "https://control-api.sigmacloud.app/access"
      - name: PUBLIC_TELEGRAM_BOT_ID
        valueFrom:
          configMapKeyRef:
            name: telegram
            key: bot-id
      - name: PUBLIC_VK_APP_ID
        value: "12345"
