{{- $name := .Values.name -}}
{{- $host := .Values.ingress.host -}}
{{- $port := .Values.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ $name }}
    spec:
      nodeSelector:
        role: application
        environment: stage
      imagePullSecrets:
        - name: google-registry-creds
      containers:
        - name: {{ $name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ $port }}
          livenessProbe:
            httpGet:
              path: /healthy
              port: {{ $port }}
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ $port }}
            initialDelaySeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
