apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ingress-nginx
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Ingress NGINX Controller"
