apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: ingress-nginx
  namespace: monitoring
spec:
  endpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - ingress-nginx
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/instance: ingress-nginx
      app.kubernetes.io/name: ingress-nginx
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaFolder
metadata:
  name: ingress-nginx
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  title: "Ingress NGINX Controller"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: ingress-nginx
  namespace: monitoring
spec:
  folderRef: ingress-nginx
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/tags/ingress-nginx-3.15.2/deploy/grafana/dashboards/nginx.json"
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDashboard
metadata:
  name: ingress-nginx-requests-performance
  namespace: monitoring
spec:
  folderRef: ingress-nginx
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/refs/tags/ingress-nginx-3.15.2/deploy/grafana/dashboards/request-handling-performance.json"
