apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infisical-secrets-production
  namespace: flux-system
spec:
  interval: 5m
  path: ./cluster-components/main/infisical-secrets-production
  prune: true
  dependsOn:
    - name: infisical-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
