apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-operator
  namespace: flux-system
spec:
  interval: 24h
  path: ./cluster-components/main/external-secrets-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
