apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-webhook
  namespace: flux-system
spec:
  interval: 24h
  path: ./cluster-components/main/flux-webhook-ingress
  prune: true
  dependsOn:
    - name: ingress-nginx
    - name: cert-issuer-selfsigned
  sourceRef:
    kind: GitRepository
    name: flux-system
