apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dragonfly-operator
  namespace: flux-system
spec:
  interval: 24h
  path: ./shared/dragonfly-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: dragonfly-operator-system
      name: dragonfly-operator-controller-manager
