apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 1m
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 1m
  url: https://grafana.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: victoria-metrics
  namespace: flux-system
spec:
  interval: 1m
  url: https://victoriametrics.github.io/helm-charts
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.31.0"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 10m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    victoria-metrics-operator:
      nodeSelector:
        role: service
      crds:
        enabled: false # installed separately with crds.yaml
        plain: false
      admissionWebhooks:
        certManager:
          enabled: true
    vmsingle:
      spec:
        nodeSelector:
          role: service
    alertmanager:
      spec:
        nodeSelector:
          role: service
    vmalert:
      spec:
        nodeSelector:
          role: service
    kube-state-metrics:
      image:
        registry: docker.io
        repository: bitnami/kube-state-metrics
        tag: "2.14.0"
    # kubeApiServer:
    #   enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    # kubeControllerManager:
    #   enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    # kubeEtcd:
    #   enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    # kubeScheduler:
    #   enabled: false # impossible to scrape on k3s without hardcoding the node IPs
    defaultDashboards:
      grafanaOperator:
        enabled: true
    grafana:
      enabled: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.8.12"
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics
        namespace: flux-system
      interval: 10m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    server:
      nodeSelector:
        role: service
      persistentVolume:
        enabled: true
    dashboards:
      enabled: true
      grafanaOperator:
        enabled: true
    vector:
      enabled: true
      customConfig:
        sinks:
          vlogs:
            request:
              headers:
                VL-Msg-Field: log.record.message,log.record.msg,log.message,log.msg,log,message,msg,_msg
