apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: games-api
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.6.3"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: games-api
    replicaCount: 1
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apis/games-api
      tag: dev-1735138535357 # {"$imagepolicy": "games-stage:games-api:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      hosts:
        - api.sigma1.games
      extraTemplates:
        - metadata:
            name: games-api-access
            annotations:
              nginx.ingress.kubernetes.io/use-regex: "true"
              nginx.ingress.kubernetes.io/rewrite-target: /$2
          spec:
            rules:
              http:
                paths:
                  - path: /access(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                      service:
                        name: access-api
                        port:
                          name: public
    metrics:
      enabled: true
    migration:
      tag: dev-1734890128233 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_STAGE
        value: "production"
      - name: PUBLIC_DOMAIN
        value: "sigma1.games"
      - name: GAMES_API_PORT
        value: "8080"
      - name: GAMES_API_INTERNAL_PORT
        value: "9090"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_GAMES_API_URL
        value: "https://api.sigma1.games"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1735138535357" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-pooler-rw"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: user
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: password
      - name: GAMES_DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: dbname
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
      - name: PUBLIC_TELEGRAM_BOT_ID
        valueFrom:
          configMapKeyRef:
            name: telegram
            key: bot-id
      - name: TELEGRAM_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegram
            key: bot-token
      - name: VK_SERVICE_TOKEN
        value: "12345"
      - name: VK_GROUP_TOKEN
        value: "54321"
      - name: BOVAPAY_API_URL
        value: "https://bovatech.cc"
      - name: BOVAPAY_API_KEY
        valueFrom:
          secretKeyRef:
            name: bovapay
            key: api-key
      - name: BOVAPAY_CALLBACK_URL
        value: "https://payment.sigmacloud.app/bovapay"
