apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBUAEvJFb/h8gD/QLuPsQqVj9CIBHd2HkJed0vNvGeKBlQqbrAbbi2h0EZ9lKmEaXrd0zLfFOo2EwcIO4YbJHDuH12OoPLD6Z27Kag5OT5wBL7aKuOXsvmHNtPDDA1/TiXytcP7zFawXocNCAjPacwTdbW/TfJ+ZhvnEueh2dqOBul94jXC2JBjKa0iOi6fFt9+sZ0PYhr8J5G7/12lxq7kM/IDgPKNvxZ2LSUofQOygz1diw0fPyVaojkE1RCk/8+kV/RLYdpbTu4mOVheuq/a02SGv4V4Ppjbt2JIzCLcAPWpxuu0oaGcjyRnp6VSw/pZu6y9a+OHKGI4LlUEZFF9AX+xDUlBqhQQ3yd4B8FomWNIN0u6+T+zhR20VbQFF7a0T/UcFSwLyp1f7tczYq2IBEB9BI50HuNaFazmcxed7QLFsAjJU1p4dSt05XWhgkRLPfg8RuIhvI9LtY3p5p5xK9zRT9oFhhZ9bU3CqMDwCQcHVbABZAeKjWfPUz6QAn3tfjB//+1qA5uuiwIgy4art6TPaYpbFhokzROLFFwKZVhu3rqibwJ5v2z4ryUFFO4AtZ0vl7FVY6me/4RXmH3W+9iUPqcjRtiP4sw/3i8oup42xK4liPJ9gS3T0MujawPk5R40TNGmLwv4htMIBGE+33TCJMjJfqJo0+5xlC5sLYnWBfPUJHxBfrOwUHL+7ah5/YoLyzwThydTqDGYTGy4eqg3JY99Wq2jc4UlpnDpdmbQWsJKAne5
  template:
    metadata:
      name: cloudflare-api-token-secret
      namespace: cert-manager
    type: Opaque
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  acme:
    email: letsencrypt@sigma-k8s.app
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: lets-encrypt-account-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token