apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: games-dragonfly-auth
  namespace: games-stage
spec:
  encryptedData:
    password: AgBYHtCuvoFTObZs6fugqoHJX5mGcweSNZYp5Jnhkv5AZnrsCormID2BBV63wZ6+ps7StSsP07zbyqvuwiXBYlj+xUc/ZpkI2kOBx5anWA8i6MUm/DL1/Qw7TyK6n3mJ18lxr9yPg3KlrI97KuuvYgM7umjif5qbjavSfFHdVa2fClk+Y8AegY93fujMHY1/ajtDSdf0UVW1guuE6SRGC4jgE2fAtyoKTeee8p9LsKQfHKpmhtgESOr5XbNay1F8NWt1ViSbmo33ldrFW4KFYgVqOsrhyzbDTNevHaviXc0WCn05Z0wb4b3XFK7r8U8UfEFO5O5W5CnPM9YQLQWSMsV4VXZoMrkdkZc6cjUjZZ+7YuYhal9eLk5T3vx1Z6erL7GPfDwNkPjZx9siGGdEhSVoE86+uxHn/Jj7j2ZEy2IE7sLhT3rheDSutD7+yTsEvOv4D9Bncck7vnq9U3lNTgDWPe22hguLOWrWSl02xZoV4sMZP0a7MrAcWZoBSl6SA/h6I+2J526jIxMQEkolvZjzbUJUQVGdIh40j9vhjF0nYKp7VIbhRx5veDqpcojMuMXt2sygmJuhUPaAQlAYTdbl1Mc8/cnWaa0Jygmw8TBJyILvyrNGiseCGvRU4biiTuVetl8q2wqVYS/+qkp1p+9aThYVuNjEsu/ihcyBoThOxuF+KGvetITGoPXDhzCl7Fuw6BmXCptQaYrWBk6Z8a49ezfAaTws9/Rmwcr631MpqA==
  template:
    metadata:
      name: games-dragonfly-auth
      namespace: games-stage
    type: Opaque
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: games-dragonfly
  namespace: games-stage
spec:
  replicas: 1
  nodeSelector:
    role: application
    environment: stage
  authentication:
    passwordFromSecret:
      name: games-dragonfly-auth
      key: password
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
