apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: payment-api
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.2.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: payment-api
    replicaCount: 1
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apis/payment-api
      tag: latest # {"$imagepolicy": "games-stage:payment-api:tag"}
    ingress:
      host: payment.sigmacloud.app
    service:
      port: 5070
    migration:
      tag: dev-1734215348191 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_STAGE
        value: "production"
      - name: PUBLIC_DOMAIN
        value: "sigma1.games"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1734215348191" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: PAYMENT_API_URL
        value: "https://payment.sigmacloud.app"
      - name: PAYMENT_API_VERSION
        value: "latest" # {"$imagepolicy": "games-stage:payment-api:tag"}
      - name: GAMES_DB_URL
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: uri
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: BOVAPAY_API_URL
        value: "https://bovatech.cc"
      - name: BOVAPAY_API_KEY
        valueFrom:
          secretKeyRef:
            name: bovapay
            key: api-key
      - name: BOVAPAY_CALLBACK_URL
        value: "https://payment.sigmacloud.app/bovapay"
