apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: access-api
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.8.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: access-api
    replicaCount: 1
    nodeSelector:
      role: application
      environment: stage
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apis/access-api
      tag: dev-1734701831912 # {"$imagepolicy": "games-stage:games-access-api:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      enabled: false
    migration:
      tag: dev-1736042635856 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: ACCESS_API_PORT
        value: "8080"
      - name: ACCESS_API_INTERNAL_PORT
        value: "9090"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1736034695004" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-pooler-rw"
      - name: GAMES_DB_HEALTH_HOST
        value: "games-db-health-pooler-rw"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: user
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: password
      - name: GAMES_DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: dbname
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
