
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackgres-ui
  namespace: stackgres
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    nginx.ingress.kubernetes.io/auth-url: https://auth.sigmacloud.app/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://auth.sigmacloud.app/oauth2/start?rd=$scheme://$host$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: Authorization
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stackgres.sigmacloud.app
      secretName: stackgres.sigmacloud.app-cert
  rules:
    - host: stackgres.sigmacloud.app
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: stackgres-restapi
                port:
                  number: 80
