apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: core-api
  namespace: games-production
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/live-api
      version: "1.2.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    name: core-api
    replicaCount: 2
    nodeSelector:
      role: application
      environment: production
    image:
      repository: europe-west4-docker.pkg.dev/sigma-games/docker/core-api
      tag: dev-1741561454444 # {"$imagepolicy": "games-production:core-api:tag"}
    ports:
      public: 8080
      internal: 9090
    resources:
      requests:
        cpu: "125m"
        memory: "128Mi"
    ingress:
      hosts:
        - api.sigma1.games
      extraTemplates:
        - metadata:
            name: core-api-access
            annotations:
              nginx.ingress.kubernetes.io/use-regex: "true"
              nginx.ingress.kubernetes.io/rewrite-target: /$2
          spec:
            rules:
              http:
                paths:
                  - path: /access(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                      service:
                        name: access-api
                        port:
                          name: public
    metrics:
      enabled: true
    migration:
      tag: dev-1741556899729 # {"$imagepolicy": "games-production:core-migrations:tag"}
    env:
      - name: CoreDb__Host
        value: "core-db-pooler-rw"
      - name: CoreDb__Username
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: user
      - name: CoreDb__Password
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: password
      - name: CoreDb__Database
        valueFrom:
          secretKeyRef:
            name: core-db-app
            key: dbname
      - name: CoreCache__Host
        value: "core-dragonfly"
      - name: CoreCache__Password
        valueFrom:
          secretKeyRef:
            name: core-dragonfly-auth
            key: password
      - name: CoreCache__Version
        value: "dev-1741561454444" # {"$imagepolicy": "games-production:core-api:tag"}
      - name: CoreNats__Url
        value: "nats://core-nats:4222"
      - name: Api__RateLimitBypassToken
        valueFrom:
          secretKeyRef:
            name: bypass-tokens
            key: rate-limit
      - name: Telegram__BotToken
        valueFrom:
          secretKeyRef:
            name: telegram
            key: bot-token
