apiVersion: v1
kind: Namespace
metadata:
  name: registry-creds
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-creds-store
  namespace: registry-creds
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-source-secret
  namespace: registry-creds
rules:
  - apiGroups: [""]
    resources:
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-source-secret
  namespace: registry-creds
subjects:
  - kind: ServiceAccount
    name: registry-creds-store
    namespace: registry-creds
roleRef:
  kind: Role
  name: read-source-secret
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: registry-creds-store
spec:
  provider:
    kubernetes:
      remoteNamespace: registry-creds
      server:
        url: "https://kubernetes.default"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
          namespace: registry-creds
      auth:
        serviceAccount:
          name: registry-creds-store
          namespace: registry-creds
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: google-registry-creds-mirror
spec:
  refreshTime: 1m
  namespaceSelectors:
    - matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: Exists
  externalSecretSpec:
    refreshInterval: "1h"
    secretStoreRef:
      kind: ClusterSecretStore
      name: registry-creds-store
    target:
      name: google-registry-creds
      template:
        type: kubernetes.io/dockerconfigjson
    data:
      - secretKey: .dockerconfigjson
        remoteRef:
          key: google-registry-creds
          property: .dockerconfigjson
