{{- $host := .Values.ingress.host -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  revisionHistoryLimit: 1
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ .Values.name }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      imagePullSecrets:
        - name: google-registry-creds
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          
          ports:
            {{- if .Values.ports.public }}
            - name: public
              containerPort: {{ .Values.ports.public }}
            {{- end }}
            {{- if .Values.ports.internal }}
            - name: internal
              containerPort: {{ .Values.ports.internal }}
            {{- end }}

          {{- if .Values.healthchecks.enabled }}
          livenessProbe:
            httpGet:
              path: /healthy
              port: {{ .Values.healthchecks.port }}
            initialDelaySeconds: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: {{ .Values.healthchecks.port }}
            initialDelaySeconds: 5
          {{- end }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
