apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  name: games-dragonfly
  namespace: games-production
spec:
  replicas: 1
  nodeSelector:
    role: application
    environment: production
  authentication:
    passwordFromSecret:
      name: games-dragonfly-auth
      key: password
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
