apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: production-games-dragonfly
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: admin
      path: /metrics
  namespaceSelector:
    matchNames:
      - games-production
  selector:
    matchLabels:
      app.kubernetes.io/name: dragonfly
      app: games-dragonfly