apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: control-api
  namespace: games-production
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/live-api
      version: "1.0.3"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: control-api
    replicaCount: 1
    nodeSelector:
      role: application
      environment: production
    image:
      repository: europe-west4-docker.pkg.dev/sigma-games/docker/apis/control-api
      tag: dev-1740690686195 # {"$imagepolicy": "games-production:control-api:tag"}
    ports:
      public: 8080
      internal: 9090
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
        nginx.ingress.kubernetes.io/auth-url: https://auth.sigmacloud.app/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://auth.sigmacloud.app/oauth2/start?rd=$scheme://$host$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-snippet: |
          if ($request_method = OPTIONS) {
            return 200;
          }
      hosts:
        - control-api.sigmacloud.app
      extraTemplates:
        - metadata:
            name: control-api-access
            annotations:
              nginx.ingress.kubernetes.io/use-regex: "true"
              nginx.ingress.kubernetes.io/rewrite-target: /$2
          spec:
            rules:
              http:
                paths:
                  - path: /access(/|$)(.*)
                    pathType: ImplementationSpecific
                    backend:
                      service:
                        name: access-api
                        port:
                          name: public
    migration:
      tag: dev-1740680312501 # {"$imagepolicy": "games-production:games-db-migration:tag"}
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_STAGE
        value: "production"
      - name: PUBLIC_DOMAIN
        value: "sigmacloud.app"
      - name: CONTROL_API_PORT
        value: "8080"
      - name: CONTROL_API_INTERNAL_PORT
        value: "9090"
      - name: PUBLIC_GAMES_APP_URL
        value: "https://sigma1.games"
      - name: PUBLIC_GAMES_API_URL
        value: "https://api.sigma1.games"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1740701492925" # {"$imagepolicy": "games-production:games-api:tag"}
      - name: PUBLIC_GAMES_WS_URL
        value: "wss://ws.sigma1.games"
      - name: PUBLIC_REDIRECT_API_URL
        value: "https://sigm.to"
      - name: PUBLIC_CONTROL_APP_URL
        value: "https://control.sigmacloud.app"
      - name: PUBLIC_CONTROL_API_URL
        value: "https://control-api.sigmacloud.app"
      - name: PUBLIC_CONTROL_API_VERSION
        value: "dev-1740690686195" # {"$imagepolicy": "games-production:control-api:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-pooler-rw"
      - name: GAMES_DB_HEALTH_HOST
        value: "games-db-health-pooler-rw"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: user
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: password
      - name: GAMES_DB_DATABASE
        valueFrom:
          secretKeyRef:
            name: games-db-app
            key: dbname
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: PUBLIC_TELEGRAM_BOT_ID
        valueFrom:
          configMapKeyRef:
            name: telegram
            key: bot-id
      - name: TELEGRAM_BOT_TOKEN
        valueFrom:
          secretKeyRef:
            name: telegram
            key: bot-token
      - name: PUBLIC_VK_APP_ID
        valueFrom:
          secretKeyRef:
            name: vk
            key: app-id
      - name: VK_APP_SECRET
        valueFrom:
          secretKeyRef:
            name: vk
            key: app-secret
      - name: VK_SERVICE_TOKEN
        valueFrom:
          secretKeyRef:
            name: vk
            key: service-token
      - name: VK_GROUP_TOKEN
        valueFrom:
          secretKeyRef:
            name: vk
            key: group-token
