apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAckN3SwtjSoOrxSdwqOL/3fxVcIbUxLkjm5ZsQ09sNtYnwiXbaW8YXKxuK0nECBcG6HeFxg4HUJ/Fmja+YRP09J+sRzbt+98W4W5GzFCDQ3IL7A4sxy7SMS7XERvjvcaOIEfXgImYS5ZPbIuKn9gUPPDJmyFfp9trjyQXYTtsLnO7AVlEHlT1oaI/eaeeIw7SohZickscta7zcWPV46jLUKaT0iCeEF47j7iWBYNqghfVCJ2HNtp0fJDvFzV1AKHjM/M7t0AtpztbyQayXYfhncxsAmTbyclyJAamKzEusNOFbdkTLX2HjOxuToohtssUAHqEcfJkHGLy8nSxG9YhpMnTP5HY0Li58dh7rlowfpyxLURsg5o2TVujXte39rwmTo/NxJJakhiSeRr2JVVmzz9amIQ+OaWBPfOxsUmsB17+pj7JcQmjU19rswp7wX47wMsmq4MYR9H9edscIJQPJN0i6nTiXMv34C4g4z/VmcI6/0i6LAyKQkdOsdVsVH+7zxV12UdznZ6Gj2okfQULSprCb0lH1mJWyIfozdhAcl+B+JKBa7vCWFd0xkNcn6nWb032/Pcm81CJb8tYz7GsFOALMwCZKNzw8Hxv5dyh3xO6f4W/VlVM++Kh2iFkhx8piTE2OHimKS75AsWJzfAOGtow1EaP/sVBBYRkbSMS10CyBeTZ2rfavJGbZMUFI4flSmqfVZgnVCvO6zerqjJgFuGdckKPQZqTewUDg+33oXnzrvjjCfPtisw==
  template:
    metadata:
      name: webhook-token
      namespace: flux-system
    type: Opaque
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stage.sigma-k8s.app
      secretName: stage.sigma-k8s.app-cert
  rules:
  - host: stage.sigma-k8s.app
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /webhooks/flux(/|$)(.*)
        backend:
          service:
            name: webhook-receiver
            port:
              number: 80