apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webhook-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgC6AHqlcH+fE7yftZ5gnw1wW9ymkrZsx3glMaX6py3CqW0njnCLWohVFWVbeyoEib98N7JrUu/OfCn6HD86xvf4llnmaynInIGMSVSkA/ZIzm7WijCj8HmqAT8V3+xTvTVqS2tPmj7i/qdeRTS2468FfEhenIBbFTSZcno/Zw1sq9KPXhoABmIrJQXcZtYO1q+mYU2izExD8xThClQuPnowYQiCkYsTYxPG+0E9aN/ObU0PLkmROL8Jl+tfD/JvJOspRxoaKo4iKX4wAnCa+gAPXjJop0Ku+ntWg1RaatxBKyBfNLYzcnjQuY6F/9u2hPF3yNL8wDs77NT8+vzBkmXzugZqTrZJSGTTKsr/7BgjJ7fzvqntl+qHoBqYq7SkRsUWIKo+uqLADf/NPHJs0o7bQvZN6EHGzRMi1pjBujmS5ZOTnsk1rgeaD1eWCds84R66AW2todTYrtjSaP9i2CU185VOgIsNsZdifxnJmFpnRYn0b6qJiM612vuECSR35woZascn32w3N8bMSBKfaQ9S41iuKKCNuVsi/VHM/g8UqJpeDB9SaVJOssM3uHmx3+ZSMxecXxWzJUYs1k4polfqR3aCPqSIq2c83XlG7plSdcgYm/+gv0goX3vC9+Qf9/n8QUMoQsGLsoh7w49dlJYVBrR71z/LTRcru1TXVLOUrVzcO2GPaMOg7HoD+OJRft/UTSVPk4BaVuEZ7ngo/OHAXZjW0m+aTudNOHoZqwTUXDErKFH0eA2C
  template:
    metadata:
      name: webhook-token
      namespace: flux-system
    type: Opaque
---
apiVersion: notification.toolkit.fluxcd.io/v1
kind: Receiver
metadata:
  name: flux-system
  namespace: flux-system
spec:
  type: github
  events:
    - "ping"
    - "push"
  secretRef:
    name: webhook-token
  resources:
    - kind: GitRepository
      name: flux-system
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webhook-receiver
  namespace: flux-system
  annotations:
    cert-manager.io/cluster-issuer: selfsigned
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - stage.sigma-k8s.app
      secretName: stage.sigma-k8s.app-cert
  rules:
    - host: stage.sigma-k8s.app
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /webhooks/flux(/|$)(.*)
            backend:
              service:
                name: webhook-receiver
                port:
                  number: 80
