apiVersion: v1
kind: Namespace
metadata:
  name: games-stage
---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: size-xs
  namespace: games-stage
spec:
  cpu: 250m
  memory: 256Mi
---
apiVersion: stackgres.io/v1
kind: SGInstanceProfile
metadata:
  name: size-sm
  namespace: games-stage
spec:
  cpu: 500m
  memory: 512Mi
