apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: jwt-secret
  namespace: games-stage
spec:
  encryptedData:
    secret: AgDLzkZhSy986VGmmyE5PEJykBOoK4MRBxG63L7WUv32jqdq0W86REUFMI9IoclCnBqP2OPs5Cl+AmOplj0FRXA1LtBBHhYfwHEhPLUq9juSeMhY9fDWdP6UWGD1yoq9Sk4F0qcFBlX62lx/RUEbZ878NHq8N9y5vIyuWQfgRvyky6RE5CUH1vNMrR0nid0B/KhVT5NcF01CIjzC43JiQnauBDV85D0zSeM9zrMavU9nWk0Qm5b8JaAde9JfP6UTwurMxqNqzIxPgyV4kA6BZS8CjthRRaOKDbjzsJjHJf0xkWORAWMJgL4dOQmyMX8IPYQUHe6mzF4VpN/enhoD1DUnhFYb5N04ifXAmqhtqWfR5pvPpeCAh9SjrkXLJ9EeDsoP/bP8Xhsrr1fr0v13o6yMcUCZgCerSoVTfHLul6KL/rSmOGkyYrhi+BWabH3spozPsmXtCoxrF5CRDdkXxdkTMWRkX+wKaC2EqxOFJU6FLqI+bpFhImH+k4+Mn+vT2VKIPw6HE+Th+QecavDG8Db5ee7nWU0O/10O8DlvBfAAjq91Be0laF5psD0SVTbaw3udBRicwZbcplu9VGiFz0JmP0MWbj1dg4ts2G3XLT/DbtL43jKGlB1yZs1f9ZYojhWpIvqF7lBGKSqOWGeKhyuybLYs9Yo2tROW+YinEm6LeK/r1m/q41uOgj6Wu7gA6WJ8/vusp2fhiWaxk1d2rW8DBnHqoMiNBNIQdGbsKnFJ9g==
  template:
    metadata:
      name: jwt-secret
      namespace: games-stage
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram
  namespace: games-stage
spec:
  encryptedData:
    bot-token: AgBiQ3EIS85biPVsUzolW7HhvYOnw1p4oRvpTK0Tmr+JIhVbWTuWNy/wumoH2AB85t24Qr3g7M/JFAccng7ppDp6olgul4leViHLHFKyawyN2ubKZeVcmI3pfAR37c9+FjnV2GSapcC46FwcZDLUDNASs9txX9MP6uLp6YOFEivbbAc2GrFHhYazC3+E57RMVV/NudzlnLLuwt1BhHlxONhlJLEOV86Q9LW3E12KiaXTSCLVw1OGd+rOIEbf7PFO30QLNRMIHEVZDruU6eKb5GeVZgC0dSOH9dzCOxS3KzPwjYAweVS/udJzo0qQVmYSQ6dojSM3tnvkcn/3HD2GohsXmYP/YgI3FGIPYTtdZH7d5RXzu8R5H3q/MMY9gu+sjYE6OCMSRVXnYuWEoidyWvYqTT8pyjHRuNDnMf7FHxuzK2ecYa9AYeNFCO5ffxkFuUYQtwh2hUyzUdVXgJtOG9EyEowSEImqMTQ9pDTiqq9/FcT7fUfWD/O3GQ53LW6X8H29zzPm6zQzunAOGW/JOWqypGN0qQwWzGBjCuIs2KuP/ioV4jw6BFI0hvn7tB1OGH/xE2BE44HT89cJc0Up0kt8x2e8XB8RVqndZvRFXrBY2+AQ51PDoZUuTJJKsD+OGq8fGT+Fq/tJEruzaiwRUIThSMTqS57VdkDYHiKpfy0E5n1bA7e7nqxspscLRzvoW+5EqjFEaWCeClpYoqGRME8J2NWXSh/hHi5Ui3966NulcVWNyw==
  template:
    metadata:
      name: telegram
      namespace: games-stage
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bovapay
  namespace: games-stage
spec:
  encryptedData:
    api-key: AgDC0C+XJCwdqVjuwiGNLu7xKLnttA5mxpJrkWqC+RL515DhUyH00q8s69yM5IwonIq7m7hm1hE7gXftUljiywapk11web47Fs0jNNv8wf+cAmx8dO9VUDW9Wgf6KjdHuIi2NCxXQsebpJhTq8243dpk9gXmm/zDI2lG4gfCqIzi8a/hIiWBycJHmG4jgQf4vYrHJ50ECCrPhNEb1tNOSchcvd5s7mK9RgtTCwZeqB3KH9Ccgikx8Yuce7y6R5h+aPiDOE4a+v5HCiyPacnYXg3He107MVML8b3T/1xagWJI7gf38PImAGHeZhK7S2V7CvQvP+RtVBpuPyXPNYYKLp/TxyFo5kElv6vPV4HztSvL+ZmQL9evER8O7YGwWaSajhwkwXW5wogD+EKdQIubBf1Ovg0EJL/CI/FJpo8jOw74mBQq0k0otB/81N0QELe2mj7rp5HOXTLKJYt93YTQp+yHONlkTVU28OeF9U7BB8qELI1Gp80gNhF2Prfn6RAEdt4KR08wl3ZFXLdmmqzQqRYXSznHC+niT1nAZ1ywUAQ6NfHZm6P2KG+pq9WWRLyn6zJbEmSYfhrSO6T5wTweH3GT/3WlHIxbXFOOTeJfhqZfkBQYZNc+ip+SiH1MBM+OoxvwJqBawdFUavS6yQGr8hBH6QMl2McT5U9+LZrofT5oIg2G6i5oNLA+mUwI1Jmu810qcJOxR4W8LLrEOSEdFVqcpsxtuIN1yCdJYjYr2ffBq/sjknxbjJhh
  template:
    metadata:
      name: bovapay
      namespace: games-stage
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: bypass-tokens
  namespace: games-stage
spec:
  encryptedData:
    waf: AgA+FgGpcxfamZjhqXTTpC38G1jPaKOacSCzWHz8QHNpbJ/FyCY9G9BtSIkuEMRWOJjmiMPU1aC2KR52t+Xf0B+ditezSnJNjDT23ZXtKZWHxRRxFG7l2CiSiatrH9sXbjw3Gw5ttfrJJsvwrMqGwIVVJnzxFeb3rg3nAY0itdOQT+kzLC55ORUFBUHOraBUsGxUcZzAWDhoCEUWI8Xux/iWGEh7Edrg0Xj+vs285hD8MHdf4OGTvh9xS6Zf7EBOHx0tVMS695dKVxWzsusx5RLZIafNBhsCmga94jg7e4FVnXiDt5I+1xlVJI5h1nl8rjQsRp1ZP+AjWUucIBmjwu92F2kzsBp+/OAjLPjZwAVn4kpg2u2SON6ch4wHoFlmYcOAvYpTfdoPtJNojyqNoBv4LwO8ViUbcmQzUy1RbSUgv2j7PL0V1NyX6Tv6h4J9XraYfa2nE4GwYME5eog2TD4NdE5NdeoBrW5IGEuxmox6I5Pe9T/7c1AU7Hp9L8UqL5Sg1izBJsvxYaichxw8neONcrhvBAnFDrZJPQ0uK8l4M/y6kr7Bzh9ED4GPWNwi+UAmlk1XWWZyvHDFtSvmNKcckJdK+QbylGwgv9SXZQff/iCZ1vmEEOcpAXciQxQ+Q1NMCY3RdnY4BM2Yi+rNDj4j9nVOK8zpbeDgOQK/WnvhOOlWwxx9XZ9OT1vD8xPGy1ZPdjMqB+9baPiZxg7O1of7US8ApFeaKIUsA+9/OvJ7XGVLZi+lg2oKCjDLg1no9v0=
    rate-limit: AgAbuLkHYLrvwqRbBYh9etnOyFyvwO86gbyE+wkUzLNPgCemHJdKdJX467Kh4Aq/0JYu5/lxfBqzqwR9tfV9FL0G4t3sDE/f0e/tTd01eW68ftqRT6RGYpLVXZCO3R6aKZrzgpyzy6YA5Rm4jNnbnEfUU4DnzG0yqi5FOjzbOVgXeQ3BcyV1qdWIEZeeXaqi9oVWDc0GcipH/+mKB9HavajH4FJUsd+J1PUJ1Eo4KK0HeT/6zbW/l9FvN4PTz5cJZ7K8nA8KOYt+uy6vbbYg9bLcZR+gp4ISHUyo96XHNSM6d/UwI0i7PmMNJC7v5nJzQaU7SYPim15o5HCjOCZv3MaQods31aV5DJVK7dzwqZkcrUfd6pbOKRmuH2+e0RVr6Q2bovr38f1Rmrxyy/DKrUQ3gPD5H2wUuaj+rdwk2XFK5zFidWNlTF+qy3kwATo/rl5/of9IIvYq9xamGcTb7fqX5CNushTgU7R0AZ295h2y5xj5TJPL7TMfTh9Gh3G0yDerH0yTjYbCCiolIhrm5f187jM0c5Fjw9X6wlPQ+n2i0XqL9W8OQRqkZYAYPSvoIYwE14Icz5dxVCUVJC+gmBA/SmvGD2C4Oa7K/9P7T/xYt0/2b46VrQhfAXvIind8WDvna7WTe4Kv2CfAOrne/+k7uDKFugeKZmdbzEFIoRmtbBkYAPryznq0Fnf73ZgQz0J0/8nZnfWhP4j6SstvuVFi2/QyBgtSQomw+CsMgLdm1tXuNoAN6W5XMqOh/epMggY=
  template:
    metadata:
      name: bypass-tokens
      namespace: games-stage
    type: Opaque
