apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: stage-payment-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/stage/04-payment-api
  prune: true
  dependsOn:
    - name: registry-creds
    - name: ingress-nginx
    - name: cert-manager
    - name: cert-issuers
    - name: stage-shared
    - name: stage-games-db
    - name: stage-games-dragonfly
    - name: stage-games-db-migration
  sourceRef:
    kind: GitRepository
    name: flux-system
