apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: games-tasks
  namespace: games-stage
spec:
  interval: 10m
  timeout: 15m
  chart:
    spec:
      chart: ./charts/prod-api
      version: "0.2.1"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  driftDetection:
    mode: enabled
  upgrade:
    remediation:
      retries: -1
  values:
    name: games-tasks
    replicaCount: 1
    image:
      repository: europe-west1-docker.pkg.dev/sigma-games/docker/apis/games-tasks
      tag: dev-1731183606194 # {"$imagepolicy": "games-stage:games-tasks:tag"}
    ingress:
      enabled: false
    service:
      port: 5053
    migration:
      tag: dev-1731168824796 # {"$imagepolicy": "games-stage:games-db-migration:tag"}
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "125m"
        memory: "128Mi"
    env:
      - name: NODE_ENV
        value: "production"
      - name: PUBLIC_STAGE
        value: "production"
      - name: PUBLIC_GAMES_API_VERSION
        value: "dev-1731168824796" # {"$imagepolicy": "games-stage:games-api:tag"}
      - name: PUBLIC_GAMES_TASKS_VERSION
        value: "dev-1731183606194" # {"$imagepolicy": "games-stage:games-tasks:tag"}
      - name: GAMES_DB_HOST
        value: "games-db-primary.games-stage"
      - name: GAMES_DB_USER
        valueFrom:
          secretKeyRef:
            name: games-db
            key: superuser-username
      - name: GAMES_DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-db
            key: superuser-password
      - name: GAMES_CACHE_HOST
        value: "games-dragonfly"
      - name: GAMES_CACHE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: games-dragonfly-auth
            key: password
      - name: JWT_SECRET
        valueFrom:
          secretKeyRef:
            name: jwt-secret
            key: secret
