replicaCount: 1

name: "example"

image:
  repository: example-api
  pullPolicy: IfNotPresent
  tag: "latest"

ports:
  # public: 8080
  # internal: 9090

healthchecks:
  enabled: true
  port: internal

service:
  enabled: true

ingress:
  enabled: true
  hosts:
    - "example.com"
  annotations: {}
  extraTemplates: []

metrics:
  enabled: false
  port: internal

migration:
  enabled: true
  tag: ""

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

env: []
