apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

configurations:
  - kustomizeconfig.yaml

resources:
  - scrapes.yaml
  - folders.yaml
  - dashboards/cloudnative-pg.yaml
  - dashboards/pgbouncer.yaml

configMapGenerator:
  - name: cloudnative-pg-dashboard
    files:
      - dashboard.json=dashboards/cloudnative-pg.json

  - name: pgbouncer-dashboard
    files:
      - dashboard.json=dashboards/pgbouncer.json
