apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: cloudnative-pg
spec:
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - cnpg-system
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
