apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-affiliate-api
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/production/040-affiliate-api
  prune: true
  dependsOn:
    - name: registry-creds-mirror
    - name: production-shared
    - name: production-core-db
    - name: production-core-dragonfly
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: games-production
      name: affiliate-api
