apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-core-tasks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/production/040-core-tasks
  prune: true
  dependsOn:
    - name: registry-creds-mirror
    - name: ingress-nginx
    - name: cloudflare-tls-mirror
    - name: production-shared
    - name: production-core-db
    - name: production-core-dragonfly
    - name: production-core-nats
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: games-production
      name: core-tasks
