apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-games-tasks
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/production/040-games-tasks
  prune: true
  dependsOn:
    - name: registry-creds
    - name: production-shared
    - name: production-games-db
    - name: production-games-dragonfly
  sourceRef:
    kind: GitRepository
    name: flux-system
