apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-control-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/production/060-control-app
  prune: true
  dependsOn:
    - name: registry-creds-mirror
    - name: ingress-nginx
    - name: cloudflare-tls-mirror
    - name: production-shared
    - name: production-maintenance-app
    - name: production-control-api
  sourceRef:
    kind: GitRepository
    name: flux-system
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: games-production
      name: control-app
