apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: production-games-app
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./stands/production/060-games-app
  prune: true
  dependsOn:
    - name: registry-creds-mirror
    - name: ingress-nginx
    - name: cloudflare-tls-mirror
    - name: production-shared
    - name: production-maintenance-app
    - name: production-games-api
    - name: production-games-ws
  sourceRef:
    kind: GitRepository
    name: flux-system
