{{- $secretsMap := dict -}}
{{- $nameTemplate := .Values.nameTemplate | default "%s-cloudflare-tls" -}}
{{- range .Values.targets -}}
  {{- $namespace := .namespace -}}
  {{- range .secrets -}}
    {{- $secret := . -}}
    {{- $key := printf $nameTemplate $secret -}}
    {{- if not (hasKey $secretsMap $key) -}}
      {{- $_ := set $secretsMap $key (dict "namespaces" (list)) -}}
    {{- end -}}
    {{- $_ := set (index $secretsMap $key) "namespaces" (append (index $secretsMap $key "namespaces") $namespace) -}}
  {{- end -}}
{{- end -}}

{{- range $secret, $data := $secretsMap }}
apiVersion: mirrors.kts.studio/v1alpha2
kind: SecretMirror
metadata:
  name: {{ $secret | replace "." "-" }}
spec:
  source:
    name: {{ $secret }}
  destination:
    namespaces:
      {{- range (uniq $data.namespaces) }}
      - {{ . }}
      {{- end }}
---
{{- end -}}
