{{- if .Values.ingress.enabled -}}
{{- if or (not .Values.service.enabled) (not .Values.ports.public) -}}
  {{- fail "When ingress is enabled, 'service.enabled' and 'ports.public' must be set" -}}
{{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "prod-api.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.annotations }}
      {{- toYaml .Values.ingress.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    {{- range $i, $host := .Values.ingress.hosts }}
    {{ $parts := splitList "." $host }}
    - hosts:
        - {{ $host }}
      secretName: {{ printf "%s.%s-cloudflare-tls" (index $parts (sub (len $parts) 2)) (index $parts (sub (len $parts) 1)) }}
    {{- end }}
  rules:
    {{- range $i, $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ $.Values.name }}
                port:
                  name: public
    {{- end }}
{{- end }}
---
{{- range $i, $template := .Values.ingress.extraTemplates }}
  {{- if not $template.metadata -}}
    {{- fail "'metadata' must be set for each ingress extra template" -}}
  {{- end -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $template.metadata.name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prod-api.labels" $ | nindent 4 }}
    {{- if $template.metadata.labels }}
      {{- toYaml $template.metadata.labels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if $.Values.ingress.annotations }}
      {{- toYaml $.Values.ingress.annotations | nindent 4 }}
    {{- end }}
    {{- if $template.metadata.annotations }}
      {{- toYaml $template.metadata.annotations | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    {{- range $i, $host := $.Values.ingress.hosts }}
    {{ $parts := splitList "." $host }}
    - hosts:
        - {{ $host }}
      secretName: {{ index $parts (sub (len $parts) 2) }}.{{ index $parts (sub (len $parts) 1) }}-cloudflare-tls
    {{- end }}
  rules:
    {{- range $i, $host := $.Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          {{- toYaml $template.spec.rules.http.paths | nindent 10 }}
    {{- end }}
---
{{- end }}