apiVersion: batch/v1
kind: Job
metadata:
  name: games-db-migration- # version is appended in kustomization.yaml
  namespace: games-production
spec:
  template:
    spec:
      nodeSelector:
        role: application
        environment: production
      imagePullSecrets:
        - name: google-registry-creds
      restartPolicy: Never
      containers:
        - name: games-db-migration
          image: europe-west4-docker.pkg.dev/sigma-games/docker/migrations/games-db-migration:dev-1736890296256 # {"$imagepolicy": "games-production:games-db-migration"}
          env:
            - name: NODE_ENV
              value: "production"
            - name: GAMES_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: games-db-app
                  key: host
            - name: GAMES_DB_USER
              valueFrom:
                secretKeyRef:
                  name: games-db-app
                  key: user
            - name: GAMES_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: games-db-app
                  key: password
            - name: GAMES_DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: games-db-app
                  key: dbname
